### ISSUE TITLE
Derive Debug, PartialEq, Eq on Filestat

### ISSUE THREAD

**Issue by kubkon** [bytecodealliance/wasi#34]
Not sure if this is the best avenue for this issue, but it would nice to have `Filestat` autoderive a couple of traits such as `Debug`, `PartialEq`, and `Eq`. This would lend itself nicely to asserts on `Filestat` structs:

```rust
assert_eq!(fstat1, fstat2, "should be equal);
```

Also, it seems that `FileStat` in the previous version of `wasi` did implement those traits which may be considered a regression for any user of this crate migrating from `0.7` to `0.9`.

**Comment by kubkon** [comment]
cc @alexcrichton @sunfishcode

**Comment by sunfishcode** [comment]
Debug seems obviously good.

I hesitate about Eq/PartialEq for `filestat` because it doesn't seem some something code should be doing outside of tests -- `dev`/`ino` are sufficient to identify a file if that's what's needed. And `atim` can spuriously change, or spuriously not change, depending on factors outside most code's control, so even tests should be cautious. Would it make sense to do `#[cfg_attr(test, derive(Eq, PartialEq))]`?

**Comment by kubkon** [comment]
Good point! Given the volatility of having `Eq` and `PartialEq`, I'm actually happy to leave it out. However, `Debug` would be most welcomed :-)

**Comment by alexcrichton** [comment]
👍 to what @sunfishcode said
