### ISSUE TITLE
Link to LICENSE from README is broken

### ISSUE THREAD

**Issue by jamescallumyoung** [bytecodealliance/wasi#54]
I was checking our the projects license when I spotted this.

As the title says, the link from README to LICENSE is broken. This is because the LICENSE file doesn't exist. 

It looks like this was broken in #9 when the project was triple licensed under Apache 2/Apache 2 w. LLVM/MIT. 

I'd suggest creating a COPYRIGHT file which explains the project is triple licenced, gives some rationale for the triple licensing an license choices, and explains what - if anything - contributors should do. Then, link this file from README and CONTRIBUTING.

If you're happy with the sugestion, I'd be happy to create a PR for the proposed changes.

**Comment by anp** [comment]
It [seems like](https://github.com/bytecodealliance/wasi#development) the generated files are based on [files from the upstream WASI spec](https://github.com/WebAssembly/WASI/tree/0ba0c5e2e37625ca5a6d3e4255a998dfaa3efc52/phases/ephemeral/witx), but those files are in a repository without a LICENSE file or other notice for their copyright. Some of the `.witx` files [also mention being derived from CloudABI](https://github.com/WebAssembly/WASI/blob/0ba0c5e2e37625ca5a6d3e4255a998dfaa3efc52/phases/ephemeral/witx/typenames.witx#L3) which appears to be under a [~BSD2 license](https://github.com/NuxiNL/cloudabi/blob/master/LICENSE) that is not mentioned here or in the upstream WebAssembly/WASI repo. If maintainers are addressing licensing questions it would be great to clarify the relationship here!

**Comment by sunfishcode** [comment]
This repo is Apache 2/ Apache 2 w. LLVM / MIT, because:
 - Some of this code may migrate to the Rust standard library, and Apache 2 / MIT are what it would use. They're also common in the Rust ecosystem.
 - Some of this code may be used in compiler output, so Apache 2 w. LLVM is useful.

A PR to update the README file would be welcome.

For the spec repo, I'm not a lawyer and don't know exactly what the situation is, but I can make a few observations. The specs are pure interfaces and documentation, with no actual code. And, the upstream specs have been removing a lot of the directly CloudABI-derived parts, and I expect will eventually remove the rest. CloudABI remains a valuable source of ideas, but at the actual interface level, WASI has a lot of unique needs that need to be designed for.

**Comment by sunfishcode** [comment]
Fixed in #68.
